services:
  - type: web
    name: ai-agent-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGODB_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: OLLAMA_BASE_URL
        value: http://localhost:11434
      - key: OLLAMA_MODEL
        value: llama3.2
      - key: TTS_SERVICE_URL
        value: http://localhost:8002
      - key: FACE_RECONSTRUCTION_URL
        value: http://localhost:8001
      - key: PYTHON_SERVICES_URL
        value: http://localhost:8000
      - key: CHROMA_URL
        value: http://localhost:8000
    dockerfilePath: ./backend/Dockerfile
    dockerContext: .