services:
  - type: web
    name: ai-agent-python-services
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_ENV
        value: production
      - key: PORT
        value: 8000
    dockerfilePath: ./Dockerfile
